// Document Engine — tier-1 (data) and tier-2 (headless render) exports.
// DOM-manipulating helpers (applyFieldHighlightCssVars, applyDocumentBodyTextStyle)
// work with any DOM implementation — real browser DOM or a linkedom shim.

export { IO_VERSION } from './core/document-io.js';
export {
  buildDocExport,
  buildFieldsExport,
  buildTemplateExport,
  buildDocumentExport,
  normalizeImportedDoc,
  isFieldsExport,
  isDocExport,
  validateRequiredFields,
  collectAllValues,
  applyDocumentValues,
  enrichComputedValues,
  collectFieldIdsInBlocks,
  collectReferencedFieldSchemaIds,
  pruneUnusedFieldSchemas,
  pruneUnusedBlockValues,
  normalizeDocumentValues,
  applySectionInstanceToBlocks,
  stripValuesFromBlocks,
  findMissingRequiredFields,
} from './core/document-io.js';

export {
  FIELD_MAPPING_KIND,
  FIELD_MAPPING_VERSION,
  isFieldMappingSpec,
  getPayloadByPath,
  sourcePathExists,
  payloadPathExists,
  unwrapMappingExpression,
  evaluateFieldMappingExpression,
  normalizeMappingResult,
  validateMappedValues,
  validateMappingSourcePaths,
  buildTargetSchemaTree,
  applyFieldMapping,
  previewFieldMapping,
  normalizeFieldMappingSpec,
  collectMappedSectionFieldKeys,
  omitMappedFields,
  buildSourcePayloadTree,
  resolveSourcePath,
  resolveMappedSourceValue,
  buildMappingResultFromRules,
  parseMappingResultToRules,
  resolveRulesToFieldsExport,
  upsertMappingRule,
  upsertMappingRules,
  createMappingRuleFromDrop,
  createMappingRulesFromDrop,
  collectRepeaterLeafFields,
  flattenSourcePayloadPaths,
  parsePathTokenContext,
  getSourceFieldsAtPath,
  resolveFieldMappingTarget,
  normalizeTableColumnSourcePath,
  parseMappingSourcePath,
  formatDateValue,
  parseDateParts,
  toIsoDateString,
  applyCustomDatePattern,
  looksLikeDateFormatSuffix,
  DEFAULT_DATE_FORMAT,
  DEFAULT_CUSTOM_DATE_FORMAT,
  formatCurrencyValue,
  formatNumericDisplay,
  parseCurrencyFormatSuffix,
  parseNumericValue,
  looksLikeCurrencyFormatSuffix,
  applyMappingFormatSuffix,
  looksLikeMappingFormatSuffix,
  DEFAULT_MAPPING_CURRENCY,
  DEFAULT_MAPPING_LOCALE,
} from './core/field-mapping.js';

export type {
  DateDisplayFormat,
  DateParts,
  FormatDateValueOptions,
  ParsedMappingSourcePath,
  CurrencyFormatSpec,
  FormatCurrencyValueOptions,
  IntegerDisplayFormat,
  NumericDisplayOptions,
} from './core/field-mapping.js';

export {
  evaluateSectionVisibility,
} from './core/section-visibility.js';

export {
  expandTableArraysInValues,
  collapseTablesInValues,
  tableRowsToFlatValues,
  flatValuesToTableRows,
  collectTableInstancesInBlocks,
  isTableRowArray,
  cloneTableBlockForRow,
  assignRowKeysForImport,
  clearTableFlatKeysInRecord,
  filterTableRowsWithContent,
  expandedValuesIncludeTable,
} from './core/field-io/table-field-io.js';

export {
  buildSectionedDocumentFromValues,
  expandSectionedDocument,
  findRepeatableSectionBlock,
  extractRepeatableSectionInstances,
  buildRepeatableInstancesFromEditor,
  resolveRepeatableSectionInstances,
  resolveRepeatablePagePlan,
  findAdjacentTableBlock,
  expandSectionFieldMap,
  isSectionInstanceArray,
  isRepeatableSectionName,
  filterEmptySections,
} from './core/field-io/sectioned-document-io.js';

export {
  generateFieldId,
  isValidFieldId,
  createDefaultSchema,
  createDefaultBlockData,
  ensureCellSchemas,
  ensureCellSchemasForRows,
  generateTableRowKey,
  resolveTableInstanceRows,
  labelToFieldKey,
  buildTableColumnsFromLabels,
  normalizeStoredColumnWidth,
  syncTableColumnKeyChanges,
  extractRowKeysFromTableValues,
  mergeTableInstanceRows,
  removeTableRowCellData,
  pruneTableCellDataForRows,
  syncBlocksAfterSchemaChange,
  applyFieldIdChange,
  resolveSchemaDefaultValue,
  convertSchemaType,
  cellFieldId,
  parseCellFieldId,
  isCellFieldId,
  listColumnCellFieldIds,
  syncColumnListSourceSettings,
  findColumnDisplayStyle,
  tagTableCellToken,
  isSchemaRequired,
  isSchemaReadonly,
  isTableCellInheritedReadonly,
  isFieldEditableInFillMode,
  ensureSchemaForFieldProperties,
  getDefaultFieldValue,
  getEmptyFieldValue,
  localTodayIso,
  buildRepeaterInstancesFromLabels,
  configureFieldHandlers,
} from './core/field-schemas.js';

export {
  getRepeaterFieldSchemas,
  normalizeRepeaterSchema,
  isLegacyRepeaterInstancesWrapper,
  createEmptyRepeaterValue,
  normalizeRepeaterValue,
  buildRepeaterPreviewDocument,
  buildRepeaterFillDocument,
  buildRepeaterInstanceDocument,
  buildRepeaterInstancePreviewDocument,
  createDefaultRepeaterTemplateDocument,
  buildRepeaterTemplateDocument,
  extractRepeaterFieldSchemasFromDocument,
  extractRepeaterValueFromDocument,
  extractRepeaterFieldValueFromBlocks,
  sanitizeRepeaterChildSchemas,
  stripForeignKeysFromRepeaterValue,
  ensureRepeaterChildSchemas,
  inferRepeaterChildSchemasFromValue,
  ensureRepeaterSchemasFromBlockValues,
  namespaceRepeaterChildTemplate,
  repeaterChildNamespacePrefix,
  repeaterHasTemplate,
  toRepeaterChildEditorFieldId,
  fromRepeaterChildEditorFieldId,
  REPEATER_CHILD_FIELD_PREFIX,
  buildRepeaterTemplateExport,
  parseRepeaterTemplateImport,
  applyRepeaterTemplateImport,
  syncRepeaterTemplateFromFillDocument,
  editorIdToRepeaterStorageKey,
  mergeRepeaterDomValues,
  extractRepeaterTemplateFromDocument,
  REPEATER_TEMPLATE_FILE_KIND,
  REPEATER_TEMPLATE_FILE_VERSION,
  repeaterHasContent,
} from './core/repeater-io.js';

export {
  buildFormulaFieldTree,
  listFormulaTableColumns,
  formatFormulaReference,
  parseFormulaReferenceSegments,
  extractFormulaReferences,
  resolveFormulaReference,
  extractFormulaDependencyFieldIds,
  renameFormulaPathInFormula,
  patchComputedFormulas,
  createFormulaSegmentRenamer,
  renameSectionInFormulas,
  renameFieldNameInFormulas,
  renameTableColumnInFormulas,
} from './core/formula-field-index.js';

export {
  evaluateComputedField,
  evaluateFormula,
  detectCircularDependency,
  extractFormulaDependencies,
  registerFormulaFunction,
  unregisterFormulaFunction,
  resetFormulaFunctions,
  getFormulaFunction,
  listFormulaFunctions,
  listFormulaPickerFunctions,
} from './core/computed-formula.js';
export type {
  FormulaFunctionDef,
  FormulaFunctionKind,
  FormulaFunctionArity,
} from './core/computed-formula.js';

export {
  ROOT_SECTION_KEY,
  DEFAULT_SECTION_NAME,
  slugSectionKey,
  deriveFieldId,
  deriveUniqueFieldName,
  allocateFieldIdentity,
  deriveCellFieldId,
  resolveSectionName,
  collectUsedSectionNames,
  allocateUniqueSectionName,
  ensureSchemaName,
  ensureSchemasHaveName,
  findFieldPlacement,
  collectFieldsInSection,
  collectUsedFieldNamesInSection,
  isFieldNameTakenInSection,
  resolveFieldIdByName,
  rebuildFieldIdsForSection,
  migrateFieldIds,
  findSectionNameForNode,
  findSectionLabelForNode,
} from './core/field-id.js';

export {
  walkSegments,
  mapSegments,
  findColumnsSegment,
  updateColumnsSegment,
} from './core/segment-tree.js';

export {
  DEFAULT_DOCUMENT_BODY_STYLE,
  DEFAULT_FIELD_VALUE_STYLE_OPTIONS,
  DEFAULT_FIELD_LINK_COLOR,
  DEFAULT_FIELD_HIGHLIGHT_STYLE,
  DOCUMENT_BODY_LINE_HEIGHT,
  EDITOR_FONT_FAMILY,
  DOCUMENT_PREVIEW_FONT_FAMILY,
  DOCUMENT_SECTION_HEADER_STYLE,
  DOCUMENT_TABLE_TEXT_STYLE,
  DOCUMENT_TABLE_HEADER_STYLE,
  DOCUMENT_TITLE_STYLE,
} from './core/document-display-defaults.js';

export {
  migratePageSetup,
  normalizeFieldHighlightStyle,
  compactFieldHighlightStyle,
  resolvePageSetupFieldHighlightStyle,
  resolvePageSetupTextStyle,
  resolvePageSetupFieldValueStyle,
  compactPageSetupStyle,
  applyFieldHighlightCssVars,
  applyDocumentBodyTextStyle,
} from './core/page-setup-styles.js';

export { isFieldEmpty, isTableCellDisplayPlaceholder, stripFieldTokenCaretAnchors, isHtmlValueEmpty } from './utils/field-values.js';
export { createEmptyImageValue, normalizeImageValue, isImageValueEmpty } from './utils/image-values.js';
export {
  stripTreeNodeIds,
  stripTreeIdsFromFieldSchemas,
  ensureTreeNodeIds,
  ensureTreeIdsInFieldSchemas,
  normalizeTemplateFieldSchemas,
} from './utils/tree-nodes.js';
export { normalizeFieldDisplayStyle, isEmptyFieldDisplayStyle, resolveFieldDisplayStyle, normalizeFontFamily, normalizeFontSize } from './utils/display-style.js';

export type {
  TextAlign,
  FieldDisplayStyle,
  FieldValueStyleOptions,
  FieldHighlightStyle,
  ColumnsSegment,
  TableSegment,
  RepeaterSegment,
  Segment,
  TreeNode,
  ImageValue,
  FieldSchema,
  DocumentSectionData,
  EditorBlock,
  TemplatePageSetup,
  FieldHandler,
} from './types.js';

